// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSyyE3c0UVZE9dBJyqox5tkwgUDwVLQ5A',
    appId: '1:465714358952:web:78465252510d87784a709d',
    messagingSenderId: '465714358952',
    projectId: 'minimal-social-app-470b5',
    authDomain: 'minimal-social-app-470b5.firebaseapp.com',
    storageBucket: 'minimal-social-app-470b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPF0Yu8VIyDpzf2BlwoeAozfXWyF9AJM8',
    appId: '1:465714358952:android:a9f65b8d1345eb004a709d',
    messagingSenderId: '465714358952',
    projectId: 'minimal-social-app-470b5',
    storageBucket: 'minimal-social-app-470b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPfDCAEoSbdUhab2J11D-sBkjEd6fFDs',
    appId: '1:465714358952:ios:f05b554ed17e54954a709d',
    messagingSenderId: '465714358952',
    projectId: 'minimal-social-app-470b5',
    storageBucket: 'minimal-social-app-470b5.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPfDCAEoSbdUhab2J11D-sBkjEd6fFDs',
    appId: '1:465714358952:ios:f05b554ed17e54954a709d',
    messagingSenderId: '465714358952',
    projectId: 'minimal-social-app-470b5',
    storageBucket: 'minimal-social-app-470b5.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSyyE3c0UVZE9dBJyqox5tkwgUDwVLQ5A',
    appId: '1:465714358952:web:444bc50a1e80f82c4a709d',
    messagingSenderId: '465714358952',
    projectId: 'minimal-social-app-470b5',
    authDomain: 'minimal-social-app-470b5.firebaseapp.com',
    storageBucket: 'minimal-social-app-470b5.firebasestorage.app',
  );

}